# Generated by Django 5.0.4 on 2024-05-07 13:59

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(max_length=250, verbose_name='عنوان برند')),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='لوگو')),
                ('brand_image_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین لوگو')),
                ('brand_image_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان لوگو')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 5, 7), verbose_name='تاریخ ساخت')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی گروه محصول',
                'verbose_name_plural': 'ویژگی های گروه محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, verbose_name='عنوان گروه کالا')),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='products/groups/', verbose_name='لوگو دسته بندی')),
                ('group_image_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین لوگو')),
                ('group_image_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان لوگو')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('cover_picture', models.ImageField(upload_to='media/product/', verbose_name='تصویر اصلی کالا')),
                ('group_image_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین کاور')),
                ('group_image_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان کاور')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت ')),
                ('product_discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('product_after_discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='قیمت پس از تخفیف')),
                ('exist_count', models.IntegerField(default=0, verbose_name='تعداد محصول')),
                ('product_view_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('product_sell_count', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 5, 7), verbose_name='تاریخ درج')),
                ('music', models.FileField(blank=True, null=True, upload_to='media/product/music/', verbose_name='صدای محصول')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand', verbose_name='برند کالا')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(max_length=200, verbose_name='مقدار ویژگی')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.feature', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی های محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(through='product.ProductFeature', to='product.feature'),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_picture', models.ImageField(upload_to='media/gallery/', verbose_name='تصویر')),
                ('product_picture_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین تصویر')),
                ('product_picture_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': ' گالری محصول',
                'verbose_name_plural': 'گالری محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_of_groups', to='product.productgroup', verbose_name='گروه کالا'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مقدار امتیاز')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='امتیاز محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر امتیاز دهنده')),
            ],
            options={
                'verbose_name': 'امتیاز محصول',
                'verbose_name_plural': 'امتیاز محصولات',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
