# Generated by Django 5.0.4 on 2024-04-23 14:47

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='brand',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 23), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 23), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 23), verbose_name='تاریخ درج'),
        ),
    ]
