# Generated by Django 5.0.4 on 2024-04-23 14:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_title',
            field=ckeditor.fields.RichTextField(max_length=100, unique=True, verbose_name='عنوان برند'),
        ),
    ]
