# Generated by Django 5.0.4 on 2024-04-23 14:47

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 23), verbose_name='تاریخ ساخت'),
        ),
    ]
