# Generated by Django 5.0.4 on 2024-05-06 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان سایت')),
                ('logo', models.ImageField(upload_to='media/', verbose_name='لوگوی سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام شبکه')),
                ('url', models.CharField(max_length=250, verbose_name='url شبکه')),
                ('logo', models.ImageField(upload_to='media/', verbose_name='لوگوی شبکه')),
            ],
            options={
                'verbose_name': 'شبکه های اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_name', models.CharField(max_length=250, verbose_name='نام متا')),
                ('meta_content', models.CharField(max_length=250, verbose_name='مقدار متا')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings.sitesettings', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'سیُو',
                'verbose_name_plural': 'سیُو',
            },
        ),
    ]
